name: "Capture Screenshot"
author: "Pace Kaneshige"
description: "Use Puppeteer to capture a screenshot from a URL."
inputs:
  source:
    description: "Source of the content to be captured, may be a URL or HTML content"
    required: true
  destination:
    description: "The destination filename the captured website will be written to"
    required: false
    default: "screenshot.png"
  delay:
    description: "The number of seconds to wait after the page finished loading before capturing the screenshot"
    required: false
    default: "0"
  full-page:
    description: "Capture the full scrollable page, not just the viewport"
    required: false
    default: "false"
  width:
    description: "Page width"
    required: false
    default: "1280"
outputs:
  path:
    description: "The filesystem path to the website screenshot"
runs:
  using: "node12"
  main: "../dist/index.js"
branding:
  icon: "camera"
  color: "blue"
