name: "Test Single"
on: push
jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ubuntu-latest]
        width: [1440]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Capture Screenshot
        id: screenshot
        uses: ./
        with:
          source: https://buy.getpeaktoday.com/overview/
          destination: github-com-pkaneshige-screenshot-website-${{ matrix.os }}-${{ matrix.width }}.png
          full-page: true
          width: ${{ matrix.width }}
